name: Github Actions CI
run-name: ghost-of-karelia is testing with GitHub Actions

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - name: Check files in the current dir
        run: |
          ls -la